const comprobatedSymbols = ['FIDAUSDT',
'XCADUSDT', 'AUDIOBTC', 'POLCUSDT', 'FLUXUSDT', 'WSIENNAUSDT', 'OXTBTC', 'ONEUSDT', 'EQXUSDT', 'NKNUSDT', 'SUKUUSDT', 'QKCBTC', 'XYOUSDT',
'STMXUSDT', 'SHIBUSDT', 'ONTUSDT', 'CVCUSDT', 'BTGUSDT', 'JSTUSDT', 'MBLUSDT', 'FOXUSDT', 'ADAUSDT', 'LINKUSDT', 'AVAXUSDT', 'ONEUSDT', 'AMPLUSDT',
'FORTHUSDT', 'IOTABTC', 'SNXUSDT', 'XYMBTC', 'OVRUSDT', 'PONDUSDT', 'FLUXUSDT', 'CHZUSDT', 'YFIUSDT', 'ALICEUSDT', 'PNTUSDT', 'RARIUSDT', 'SANDUSDT',
'ERNUSDT', 'MCUSDT', 'ELONUSDT', 'PONDUSDT', 'FILUSDT', 'FARMUSDT', 'ETHLOOM', 'BTCLOOM', 'USDTGODS', 'BTCAMB'];

const failsSymbolsBinance = ['BTGUSDT', 'OXTBTC', 'BEAMUSDT', 'CELRETH','DNTUSDT', 'CVCETH', 'HNTBTC', 'FIROETH', 'BTGETH', 'DLTBTC', 'POAETH', 'DOGEUSDC', 'RDNETH', 'FTMUSDC', 'WINGSBTC', 'CNDETH', 'HCETH', 'APPCETH', 'EVXETH', 'GVTETH', 'MDAETH', 'HSRBTC', 'BCPTETH', 'STRATETH', 'CHATBTC', 'PPTETH', 'POEBTC', 'SALTETH', 'BCDETH', 'TNBETH', 'SALTBTC', 'NCASHBTC', 'STRATBTC', 'RGTUSDT', 'ANKRUSDC', 'SNGLSBTC', 'TUSDETH', 'HCUSDT', 'NBSBTC', 'OSTETH', 'BCNBTC', 'BTCUST', 'USTUSDT', 'ETCUSDC', 'ETHUST', 'COVERETH', 'AMBETH', 'CONVERETH', 'BCHSVBTC', 'KSMAUD', 'EZETH', 'HCBTC', 'NUUSDT', 'AEETH', 'LUNAEUR', 'NULSETH', 'RCNBTC', 'ETHPAX', 'MBLBTC', 'MFTBTC', 'NANOUSDT', 'XRPPAX', 'DOCKETH', 'ANYUSDT', 'DFETH', 'QSPETH', 'QLCETH', 'FRONTETH', 'BTCPAX', 'XLMUSDC', 'NASETH', 'OAXETH', 'NBSUSDT', 'TNBBTC', 'BATUSDC', 'NANOETH', 'WINBTC', 'RSRBTC', 'REEFBTC', 'BCDBTC', 'KEYBTC', 'DNTETH', 'NANOBTC', 'DYDXETH', 'NASBTC', 'ALGOUSDC', 'HEGICETH', 'XEMETH', 'AEBTC', 'WTCETH', 'VOXELETH', 'DAIBTC', 'REQETH', 'FARMETH', 'AKROBTC', 'EPSUSDT', 'BCHSVUSDT', 'HNTUSDT', 'DGDETH', 'BCHSVUSDC', 'WNXMBTC', 'ETHTUSD', 'SUSDETH', 'GHSTETH', 'SYSETH', 'ASTETH', 'BNBUSDC', 'BZRXUSDT', 'TCTUSDT', 'VIDTUSDT', 'VIDTBTC', 'DATAETH', 'CKBBTC', 'BTGBTC', 'AIONETH', 'ADAUSDC', 'ZECUSDC', 'SCBTC', 'EPSBTC', 'ATOMUSDC', 'SOLUSDC', 'BTCTUSD', 'STORJETH', 'LTCUSDC', 'TRXUSDC', 'XRPUSDC', 'EOSUSDC', 'LINKUSDC', 'BCHUSDC', 'ETHUSDC', 'WAVESUSDC', 'BTCUSDC', 'USDCUSDT', 'MCOUSDT', 'DENTETH', 'GRSBTC', 'XVGBTC', 'CDTBTC', 'CDTETH', 'XRPTUSD', 'QSPBTC', 'POLYUSDT', 'KEEPUSDT', 'GNOBTC', 'DAIUSDT', 'SUSDUSDT', 'GXSUSDT', 'XVSUSDT', 'MIRUSDT', 'VGXUSDT', 'GXSBTC', 'WAVESUSDT', 'VGXUSDT', 'TORNUSDT', 'TUSDUSDT', 'FTTUSDT', 'FTTBTC', 'FTTETH', 'SRMBTC', 'SRMUSDT', 'GTOUSDT', 'GTOBTC', 'CVCUSDT', 'REPBTC', 'VGXETH', 'CVCBTC', 'PNTBTC', 'DENTBTC', 'XEMBTC', 'MITHUSDT', 'ANCUSDT', 'REPUSDT', 'BTSBTC', 'STMXETH', 'ICXETH', 'MDTUSDT'];

const failKucoin = ['ACAUSDT', 'ACABTC'];

const failBitget = ['SRMUSDT', 'GTOUSDT'];

const failHuobi = ['ANCUSDT'];

const failMexc = ['QIUSDT', 'MDTUSDT'];

const failGateio = ['DATAUSDT', 'OAXUSDT', 'QIUSDT'];

const failDigifinex = ['REIUSDT', 'GALUSDT', 'MDTUSDT'];


module.exports = { comprobatedSymbols, failsSymbolsBinance, failKucoin, failBitget, failHuobi, failMexc, failGateio, failDigifinex }